### ISSUE TITLE
Homeproxy使用二进制的srs文件提示不支持的版本

### ISSUE THREAD

**Issue by ali2liu** [REIJI007/AdBlock_Rule_For_Sing-box#2]
Singbox日志：
+0000 2024-10-19 14:55:15 ERROR router: fetch rule-set cfg-12700b5da54238bb973df447d27e58eb-rule: unsupported version: 2

**Comment by REIJI007** [comment]
那就回退version 1,因为我一直是使用sing-box 1.9.4编译的srs文件
